[package]
name = "simple"
version = "0.1.0"
authors = ["Eishun Kondoh <shun3382@gmail.com>"]
edition = "2018"

[dependencies]
pnet = "0.26.0"
nix = "0.18.0"
mac_address = "1.0.2"
eui48       = "0.4.6"
vr_type = { path = "../../../vr_type" }
